[package]
name = "auth"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
sqlx = {version = "0.8.6", features = ["runtime-tokio-rustls", "postgres", "chrono"]}

[dev-dependencies]
tokio = { version = "1.49.0", features = ["full"] }

